app/core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("weathapp.urls")),  # Makes all root urls go to weathapp
    path("weathapp/", include("weathapp.urls")),
    path("admin/", admin.site.urls),
]

app/weathapp/urls.py
from django.urls import path
from . import views

app_name = "weathapp"
urlpatterns = [
    path("", views.async_user_list, name="async_user_list"),
    path("users/", views.UsersView.as_view(), name="user_list"),
    path("weather_call/<str:zip>/<str:phone>",
         views.weather_call, name="weather_call"),
    path("weather_call/<str:zip>",
         views.weather_call, name="weather_call"),
    path("send_all/", views.send_all, name="send_all"),
]

app/weathapp/models.py
from django.db.models import CheckConstraint, Q, F
from django.db import models
import re
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


def validate_phone(value):
    """Verify phone format is like +13104318777"""
    if not re.match(r"^\+\d{10,}$", value):
        raise ValidationError(
            _("%(value)s is not valid phone. Must be like +13104318777"),
            params={"value": value},
        )


def validate_zip(value):
    """Verify zip code format is 5 digits"""
    if not re.match(r"^\d{5}$", value):
        raise ValidationError(
            _("%(value)s is not valid zip code. Must be five digit number"),
            params={"value": value},
        )


class AppUser(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=12, validators=[validate_phone])
    zip = models.CharField(max_length=5, validators=[validate_zip])

    def __str__(self):
        return f"{self.name}, ({self.phone}), {self.zip}"

app/weathapp/views.py
from django.db.models import F
from django.shortcuts import render
from django.views import generic
from asgiref.sync import sync_to_async
from .models import AppUser
from .utils import get_weather, do_call

import logging
logger = logging.getLogger(__name__)


@sync_to_async
def get_users():
    return list(AppUser.objects.all())


async def async_user_list(request):
    logger.info("Rendering user list page.")
    users = await get_users()
    context = {"users": users}
    return render(request, "weathapp/index.html", context)


class UsersView(generic.ListView):
    template_name = "weathapp/users.html"
    context_object_name = "user_list"

    def get_queryset(self):
        """Return first 50 Users"""
        return AppUser.objects.all()[:50]


def weather_call(request, zip, phone=''):
    weather_results = get_weather(zip)
    twilio_results = ""
    if phone:
        twilio_results = do_call(phone, weather_results)
    context = {"weather_results": weather_results,
               "twilio_results": twilio_results}
    return render(request, "weathapp/results.html", context)


async def send_all(request):
    users = await get_users()
    results_list = []
    for user in users:
        weather_results = get_weather(user.zip)
        twilio_results = do_call("+13104318777", weather_results)
        results_list.append(weather_results + " " + twilio_results)

    context = {"results_list": results_list}
    return render(request, "weathapp/send-all-results.html", context)

app/weathapp/templates/weathapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <link rel="stylesheet" href="{% static 'app.css' %}">
    <head>
        <meta name="description"
              content="Weather App to fetch weather data based on zip code and phone number.">
        <meta name="keywords"
              content="Weather, Zip Code, Phone Number, Weather App">
        <title>Weather App</title>
        <script>
        /**
        * Wraps the api call to fetch weather data based on zip code and phone number.
        * @param {string} zip - The zip code to fetch weather data for.
        * @param {string} phone - OPTIONAL - The phone number to text the weather data to.
        * @param {string} selector - OPTIONAL - where to write the results

        */
        function weatherCall(zip, phone='', selector='#output') {
            setContent(selector, 'Loading.........');

            // If optional phone has been provided, append it to the URL
            var url = `/weathapp/weather_call/${zip}`;
            if (phone) {
                url += `/${phone}`;
            }

            fetch(url)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.text();
                })
                .then(data => {
                    if (selector) {
                        setContent(selector, data);
                    } else {
                        return data;
                    }
                })
                .catch(error => {
                    console.error('There was a problem with the fetch operation:', error);
                });
        }

        /**
        * Sets the inner HTML of a specified element.
        * @param {string} divSelector - The selector for the element to update.
        * @param {string} value - The value to set as the inner HTML.
        */
        function setContent(divSelector, value) {
            document.querySelector(divSelector).innerHTML = value;
        }
        </script>
    </head>
    <body>
        <h1>Weather App</h1>
        {% if users %}
            <h2>API</h2>
            <div class="api">
                <p>
                    Weather only: <code>/weathapp/weather_call/{zip_code}</code>
                </p>
                <p>
                    Weather, and text it: <code>/weathapp/weather_call/{zip_code}/{phone_number}</code>
                </p>
                <p>
                    Weather and text EVERYBODY: <code>/weathapp/send_all</code>
                </p>
            </div>
            <br />
            <br />
            <h2>QUICK CALL</h2>
            <div>
                <input type="text" id="zip" placeholder="Zip Code">
                <input type="text" id="phone" placeholder="(Optional) Phone">
                <button id="callButton">Call</button>
                <script>
                    document.getElementById('callButton').addEventListener('click', function() {
                        const zip = document.getElementById('zip').value;
                        const phone = document.getElementById('phone').value;
                        weatherCall(zip, phone, '#callResult');
                    });
                </script>
                <div>
                    <p id="callResult"></p>
                </div>
            </div>
            <div>
                <p>Click the button to get the weather for the zip code and phone number you enter.</p>
                <p>Note: The phone number is optional. If you don't want to text it, leave it blank.</p>
            </div>
            <br />
            <br />
            <h2>SAMPLE USER/CALL LIST</h2>
            <div>
                This list demonstrates using the a list of call/users for the API.
                <br />
                <ul>
                    <li>Click a Zip Code to just get the weather.</li>
                    <li>Click the phone number to get weather AND text it.</li>
                </ul>
                (The (async) clicks make same call but update the page asynchronously, instead of redirecting.)
            </div>
            <br />
            <table class="styled-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Zip Code</th>
                        <th>Phone Number</th>
                    </tr>
                </thead>
                {% for user in users %}
                    <tr>
                        <td>{{ user.name }}</td>
                        <td>
                            <a href="{% url 'weathapp:weather_call' zip=user.zip %}">{{ user.zip }}</a>
                            (<a href="#" onClick="weatherCall('{{ user.zip }}')">async</a>)
                        </td>
                        <td>
                            <a href="{% url 'weathapp:weather_call' zip=user.zip phone=user.phone %}">{{ user.phone }}</a>
                            (<a href="#" onClick="weatherCall('{{ user.zip }}', '{{ user.phone }}')">async</a>)
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <h3>
                Use the <a href="{% url 'weathapp:send_all' %}">SEND ALL</a> endpoint to send the weather to all users.
            </h3>
        {% else %}
            <p>No users are available.</p>
        {% endif %}
        <p>
            <a href="{% url 'admin:index' %}">ADMIN</a> of the list
        </p>
        <div id="output"></div>
    </body>
</html>

app/weathapp/templates/weathapp/results.html
<div style="text-align: center;margin-top: 20px;">
    <h2>{{ weather_results }}</h2>
    <h4>{{ twilio_results }}</h4>
</div>

app/weathapp/templates/weathapp/send-all-results.html
<h2>SEND ALL RESULTS</h2>
{% for r in results_list %}<p>{{ r }}</p>{% endfor %}
<hr />
<a href="{% url 'weathapp:async_user_list' %}">Back</a>

app/weathapp/templates/weathapp/users.html
{% if user_list %}
  <ul>
    {% for user in user_list %}
      <li>
        <a href="{% url 'weathapp:weather_call' zip=user.zip %}">{{ user }}</a>
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>None are available.</p>
{% endif %}